# Generated by Django 5.2.7 on 2026-01-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0003_podopieczny_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTreningowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=70)),
                ('opis_cwiczenia', models.TextField(blank=True, null=True)),
                ('ilosc_powtorzen', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trener',
            name='cwiczenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_journal.plantreningowy'),
        ),
    ]
