# Generated by Django 5.2.7 on 2026-01-25 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0004_plantreningowy_trener_cwiczenie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='cwiczenie',
        ),
        migrations.AddField(
            model_name='podopieczny',
            name='plan_treningowy',
            field=models.ForeignKey(null = True, blank = True, on_delete=django.db.models.deletion.CASCADE, to='workout_journal.plantreningowy'),
            preserve_default=False,
        ),
    ]
