# Generated by Django 5.2.7 on 2026-01-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0005_remove_trener_cwiczenie_podopieczny_plan_treningowy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podopieczny',
            name='plan_treningowy',
        ),
    ]
