# Generated by Django 5.2.7 on 2026-01-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0006_remove_podopieczny_plan_treningowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='plan_treningowy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout_journal.plantreningowy'),
            preserve_default=False,
        ),
    ]
