# Generated by Django 5.2.7 on 2026-01-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0007_podopieczny_plan_treningowy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantreningowy',
            name='ilosc_powtorzen',
        ),
        migrations.RemoveField(
            model_name='plantreningowy',
            name='opis_cwiczenia',
        ),
        migrations.AddField(
            model_name='trener',
            name='plan_treningowy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout_journal.plantreningowy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cwiczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=70)),
                ('opis_cwiczenia', models.TextField(blank=True, null=True)),
                ('ilosc_powtorzen', models.IntegerField()),
                ('ilosc_serii', models.IntegerField()),
                ('dodaj_do_plan_treningowy', models.ManyToManyField(to='workout_journal.plantreningowy')),
            ],
        ),
    ]
