# Generated by Django 5.2.7 on 2026-01-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0008_remove_plantreningowy_ilosc_powtorzen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwiczenie',
            name='dodaj_do_plan_treningowy',
        ),
    ]
