# Generated by Django 5.2.7 on 2026-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0009_remove_cwiczenie_dodaj_do_plan_treningowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwiczenie',
            name='dodaj_do_plan_treningowy',
            field=models.ManyToManyField(to='workout_journal.plantreningowy'),
        ),
    ]
