# Generated by Django 5.2.7 on 2026-01-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0010_cwiczenie_dodaj_do_plan_treningowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreningowy',
            name='cwiczenia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout_journal.cwiczenie'),
            preserve_default=False,
        ),
    ]
