# Generated by Django 5.2.7 on 2026-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0011_plantreningowy_cwiczenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantreningowy',
            name='cwiczenia',
        ),
        migrations.AddField(
            model_name='plantreningowy',
            name='cwiczenia',
            field=models.ManyToManyField(to='workout_journal.cwiczenie'),
        ),
    ]
