# Generated by Django 5.2.7 on 2026-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0012_remove_plantreningowy_cwiczenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podopieczny',
            name='plan_treningowy',
        ),
        migrations.AddField(
            model_name='podopieczny',
            name='plan_treningowy',
            field=models.ManyToManyField(to='workout_journal.plantreningowy'),
        ),
    ]
