# Generated by Django 5.2.7 on 2026-01-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0013_remove_podopieczny_plan_treningowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='plan_treningowy',
        ),
    ]
