# Generated by Django 5.2.7 on 2026-01-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0014_remove_trener_plan_treningowy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stanowisko',
            new_name='Specjalizacja',
        ),
    ]
