# Generated by Django 5.2.7 on 2026-01-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0015_rename_stanowisko_specjalizacja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trener',
            old_name='stanowisko',
            new_name='specjalizacja',
        ),
    ]
