# Generated by Django 5.2.7 on 2026-01-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0017_trener_wlasciciel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_journal.trener'),
        ),
    ]
