# Generated by Django 5.2.7 on 2026-01-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_journal', '0018_podopieczny_trener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwiczenie',
            name='dodaj_do_plan_treningowy',
        ),
    ]
